version: '3.1'

services:

  db:
    ports:
        - 5432:5432
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080